# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestAdvanceBlock' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestAdvanceBlock

  target 'TestAdvanceBlockTests' do
    inherit! :search_paths
    # Pods for testing

	pod 'fishhook'
  end

end
